services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.1
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"

  weaviate-console:
    image: semitechnologies/weaviate-console
    ports:
      - "8081:80"
    depends_on:
      - weaviate
